#' Get and clean all stocks listed in AMEX, NASDAQ, and NYSE
#'
#' @return a data.table
#'
#' @export
#'
#'
get_all_stocks <- function(){
    # extract all stocks listed in AMEX, NASDAQ, and NYSE and convert
    # market cap into Billion dollars
    all_stocks <- TTR::stockSymbols() %>%
        setDT() %>%
        # cap in billion dollars
        .[, cap := as.numeric(str_extract(MarketCap, "[0-9]+")) * 1e-9] %>%
        .[str_detect(MarketCap, "M"),
          cap := as.numeric(str_extract(MarketCap, "[0-9]+")) * 0.001] %>%
        .[str_detect(MarketCap, "B"),
          cap := as.numeric(str_extract(MarketCap, "[0-9]+"))]

    return(all_stocks)
}


#' Select from a pool of stocks whose market caps are in the given range
#'
#' @param stocks a subset of all stocks generated by \link{get_all_stocks}
#' @param from,to lower and upper limits of market cap to be selected.
#'
#' @return a data.table
#'
#' @export
#'


select_cap <- function(stocks, from, to){
    selected <- stocks %>%
        .[cap > from] %>%
        .[cap < to]

    return(selected)
}


#' Select from a pool of stocks whose last trading price are in the given range
#'
#' @param stocks a subset of all stocks generated by \link{get_all_stocks}
#' @param from,to lower and upper limits of last trading price to be selected.
#'
#' @return a data.table
#'
#' @export
#'

select_price <- function(stocks, from, to){
    selected <- stocks %>%
        .[LastSale > from] %>%
        .[LastSale < to]

    return(selected)
}


#' convert tidyquant::tq_get data() to quantmod::getSymbols() data
#'
#' @param dq_df a data frame downloaded by tidyquant::tq_get()
#'
#' @return a data.frame of format getting by quantmod::getSymbols()
#'
#' @export
#'
tq2qm <- function(tq_df){
    symbol <- unique(tq_df$symbol)
    xts_object <- tq_df %>%
        .[, symbol := NULL] %>%
        setnames(
            c("open", "high", "low", "close", "volume", "adjusted"),
            paste0(symbol, ".", c(
                "Open", "High", "Low", "Close", "Volume", "Adjusted"
            ))
        ) %>%
        as.xts()

    return(xts_object)
}



#' Get price changes of stocks in last 5 trading days
#'
#' @description To search for stocks whose price rose or fell beyond a certain
#' value in the past n trading days.
#'
#' @param stocks a vector of stocks to select from
#' @param keep_days integer, keep data for the past few trading days
#' @param past_days integer, download data from a few days ago
#' @return a data.table
#'
#' @export
#'
get_change <- function(stocks, keep_days =3, past_days = 7){
    # get one week data first then select last n_days
    df <- tq_get(stocks,
                 get = "stock.prices",
                 from = Sys.Date() - past_days,
                 to = Sys.Date()) %>%
        setDT() %>%
        .[, change := c(0, diff(close)) / shift(close) * 100, by = symbol] %>%
        .[, .SD[c((.N - keep_days + 1) : .N)], by = symbol]

    return(df)
}

